### ISSUE TITLE
OPPO手机报错。

### ISSUE THREAD

**Issue by nbwzlyd** [easemob/kefu-android-demo#73]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/heytap/mcssdk/PushManager;
        at com.hyphenate.push.platform.oppo.a.b(Unknown Source:0)
        at com.hyphenate.push.platform.a.a(Unknown Source:6)
        at com.hyphenate.push.EMPushHelper.a(Unknown Source:149)
        at com.hyphenate.push.EMPushHelper.register(Unknown Source:37)
        at com.hyphenate.chat.EMClient$7.run(Unknown Source:210)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.heytap.mcssdk.PushManager" on path: DexPathList[[zip file "/data/app/~~FfG8iQC4jTtH93nBFx8-lg==/com.laizezhijia-W-BXi6R3xXnHM6p6adKsVQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~FfG8iQC4jTtH93nBFx8-lg==/com.laizezhijia-W-BXi6R3xXnHM6p6adKsVQ==/lib/arm64, /data/app/~~FfG8iQC4jTtH93nBFx8-lg==/com.laizezhijia-W-BXi6R3xXnHM6p6adKsVQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64, /vendor/lib64, /odm/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.hyphenate.push.platform.oppo.a.b(Unknown Source:0) 
        at com.hyphenate.push.platform.a.a(Unknown Source:6) 
        at com.hyphenate.push.EMPushHelper.a(Unknown Source:149) 
        at com.hyphenate.push.EMPushHelper.register(Unknown Source:37) 
        at com.hyphenate.chat.EMClient$7.run(Unknown Source:210) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923)

**Comment by nbwzlyd** [comment]
用1.2.3版本就好了，1.2.4-1.2.5总是报错
